name: ipydatagrid-test
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - nodejs=14
  - yarn
  - ipywidgets >=7.6.0,<8
  - traitlets >=4.3.0
  - traittypes >=0.0.6
  - numpy >=1.10.4,<2.0.0
  - pandas >=1.0.0,<2.0.0
  - bqplot
  - scipy
  - jupyterlab
  - jupyter-packaging
  - pytest
  - nbval
  - pytest-cov
  - selenium
  - flake8
  - nose
  - codespell
